Traceback (most recent call last):
  File "/Users/smontano/anaconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/smontano/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smontano/anaconda3/lib/python3.11/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smontano/anaconda3/lib/python3.11/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smontano/anaconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/smontano/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/smontano/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/smontano/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
model <- lm(log(wage) ~ educ + exper + expersq + female, data = wage1)
e <- model$residuals

par(mfrow=c(1,2))
hist(e, xlab = "Residuals", probability = T, ylim = c(0, 1)) #Histograma de esiduales
lines(density(e, na.rm=T), lwd = 2, col = "red") # Densidad estimada de los residuales
curve(dnorm(x, mean = mean(e, na.rm=T), sd = sd(e, na.rm=T)), lty = 2, lwd = 2, add = TRUE, col = "blue") #Distribucion normal
qqnorm(rstandard(model), col="red", pch=20) ##Q-Q plot
abline(a=0, b=1, col="blue", lty=2, lwd=2)
------------------

Error in eval(mf, parent.frame()): object 'wage1' not found
Traceback:

1. eval(mf, parent.frame())
2. eval(mf, parent.frame())
3. stats::model.frame(formula = log(wage) ~ educ + exper + expersq + 
 .     female, data = wage1, drop.unused.levels = TRUE)
4. model.frame.default(formula = log(wage) ~ educ + exper + expersq + 
 .     female, data = wage1, drop.unused.levels = TRUE)
5. is.data.frame(data)
6. .handleSimpleError(function (cnd) 
 . {
 .     watcher$capture_plot_and_output()
 .     cnd <- sanitize_call(cnd)
 .     watcher$push(cnd)
 .     switch(on_error, continue = invokeRestart("eval_continue"), 
 .         stop = invokeRestart("eval_stop"), error = NULL)
 . }, "object 'wage1' not found", base::quote(eval(mf, parent.frame())))
ERROR: Error in eval(mf, parent.frame()): object 'wage1' not found


